#ifndef BROWSER_STUBS_H
#define BROWSER_STUBS_H

static const char BROWSER_STUBS_JS[] = 
    "var Intl = {"
    "  NumberFormat: function() { this.format = function(n) { return String(n); }; },"
    "  DateTimeFormat: function() { this.format = function(d) { return String(d); }; },"
    "  ListFormat: function() { this.format = function(l) { return l.join(', '); }; },"
    "  PluralRules: function() { this.select = function() { return 'other'; }; }"
    "};"
    "Intl.NumberFormat.supportedLocalesOf = function() { return []; };"
    "Intl.DateTimeFormat.supportedLocalesOf = function() { return []; };"
    "Intl.ListFormat.supportedLocalesOf = function() { return []; };"
    "Intl.PluralRules.supportedLocalesOf = function() { return []; };"
    ""
    "function EventTarget() { this._listeners = {}; }"
    "EventTarget.prototype.addEventListener = function(t, f) {"
    "  if (!this._listeners[t]) this._listeners[t] = [];"
    "  this._listeners[t].push(f);"
    "};"
    "EventTarget.prototype.removeEventListener = function(t, f) {"
    "  if (!this._listeners[t]) return;"
    "  var i = this._listeners[t].indexOf(f);"
    "  if (i >= 0) this._listeners[t].splice(i, 1);"
    "};"
    "EventTarget.prototype.dispatchEvent = function(e) {"
    "  e.target = this; e.currentTarget = this;"
    "  var ls = this._listeners[e.type] || [];"
    "  for (var i = 0; i < ls.length; i++) try { ls[i].call(this, e); } catch(x) {}"
    "  return !e.defaultPrevented;"
    "};"
    ""
    "function Event(t, o) {"
    "  this.type = t || '';"
    "  this.bubbles = !!(o && o.bubbles);"
    "  this.cancelable = !!(o && o.cancelable);"
    "  this.target = null;"
    "  this.currentTarget = null;"
    "  this.defaultPrevented = false;"
    "  this.timeStamp = Date.now();"
    "}"
    "Event.prototype.preventDefault = function() { if (this.cancelable) this.defaultPrevented = true; };"
    "Event.prototype.stopPropagation = function() {};"
    ""
    "function HTMLElement() {"
    "  EventTarget.call(this);"
    "  this.style = {};"
    "  this.classList = { add: function() {}, remove: function() {}, contains: function() { return false; } };"
    "  this.className = '';"
    "  this.id = '';"
    "  this.innerHTML = '';"
    "  this.textContent = '';"
    "}"
    "HTMLElement.prototype = Object.create(EventTarget.prototype);"
    "HTMLElement.prototype.constructor = HTMLElement;"
    ""
    "var document = {"
    "  body: null,"
    "  head: null,"
    "  createElement: function(t) { return new HTMLElement(); },"
    "  getElementById: function() { return null; },"
    "  querySelector: function() { return null; },"
    "  querySelectorAll: function() { return []; },"
    "  addEventListener: function() {},"
    "  removeEventListener: function() {},"
    "  dispatchEvent: function() { return true; }"
    "};"
    "document.body = new HTMLElement();"
    "document.head = new HTMLElement();"
    ""
    "var window = {"
    "  document: document,"
    "  navigator: { userAgent: 'Mozilla/5.0', language: 'en-US', languages: ['en-US'] },"
    "  location: { href: 'https://www.youtube.com', hostname: 'www.youtube.com' },"
    "  history: { pushState: function() {}, replaceState: function() {} },"
    "  localStorage: { getItem: function() { return null; }, setItem: function() {}, removeItem: function() {} },"
    "  sessionStorage: { getItem: function() { return null; }, setItem: function() {}, removeItem: function() {} },"
    "  console: { log: function() {}, error: function() {}, warn: function() {} },"
    "  addEventListener: function() {},"
    "  removeEventListener: function() {},"
    "  dispatchEvent: function() { return true; },"
    "  setTimeout: function(f) { if (typeof f === 'function') f(); return 0; },"
    "  clearTimeout: function() {},"
    "  setInterval: function() { return 0; },"
    "  clearInterval: function() {},"
    "  requestAnimationFrame: function(f) { if (typeof f === 'function') f(0); return 0; },"
    "  cancelAnimationFrame: function() {},"
    "  fetch: function() { return Promise.reject(new Error('fetch not supported')); },"
    "  XMLHttpRequest: function() {"
    "    this.open = function() {};"
    "    this.send = function() {};"
    "    this.setRequestHeader = function() {};"
    "    this.readyState = 4;"
    "    this.status = 200;"
    "    this.responseText = '{}';"
    "  }"
    "};"
    "window.window = window;"
    "window.self = window;"
    "window.top = window;"
    "window.parent = window;"
    ""
    "var console = window.console;"
    "var navigator = window.navigator;"
    "var location = window.location;"
    "var history = window.history;"
    "var localStorage = window.localStorage;"
    "var sessionStorage = window.sessionStorage;"
    "";

#endif
